### ISSUE TITLE
[Feature] InitScript support for Coffin DSL

### ISSUE THREAD

**Issue by addisonj** [chrisfjones/coffin#9]
Hi Chris,

Thanks for accepting those last PRs. Glad to be able to help.

I was playing around with the InitScript function. Its really nice to make readable scripts.

I ran into one problem though, as this doesn't seem to work

``` CoffeeScript
@InitScript """
  echo "I am in region #{@Region} # anything with #DSL sytax
"""
```

It ends up producing output with `@Region` compiling to `[Object object]`

This technically seems like it might be kinda difficult, but do you have any thoughts on this?

**Comment by chrisfjones** [comment]
Ah yes, that snuck in there with the switch to Ref: 'AWS::Region'. I'll add a test and make sure that does an eval instead of assuming its a string.

**Comment by addisonj** [comment]
I have the same behavior for all the DSL features.

another example

```
@InitScript  '"""
echo "#{Params.MyParamName}"
"""
```

That also just returns `[Object object]`

**Comment by chrisfjones** [comment]
On closer inspection, it looks like the coffeescript evaluation is happening first so it resolves #{blah} before coffin can do anything about it. The options seem to be:
1. change the template syntax for @InitScript to something other than coffeescript's #{}
2. require users to use the ' ' or ''' ''' quotations instead of " " or """ """

Option 1 would be a breaking change for all the InitScripts already out there in the wild, but I know people will run into the same problem if they can't use " and """. What are your thoughts?

p.s. Another alternative is to put the script content in a file instead of inline, this isn't documented very well but it works like this:
UserData: @InitScript 'filename.sh'

**Comment by addisonj** [comment]
Ah, I understand, makes sense.

I would say, ultimate goals should be:
1. Allow heredocs and files (because heredocs are awesome and much easier to read)
2. Have the behavior and syntax be the same for both
3. Not have to use Fn:Join manually

While not being able to use `#{}` is the cost to pay, that might be worth it. This is a DSL anyways, so perhaps just something like `${}`

**Comment by chrisfjones** [comment]
Cool, I agree. I've added version 0.2.1 which changes the syntax to %{}
because ${} is syntax already used in shell scripts. I've also added a
CHANGELOG.md to help notify users of breaking changes.

Cheers,
-Chris
